#!/bin/bash
#PBS -N run.pbs
#PBS -l mem=16gb
#PBS -l walltime=8:59:00
#PBS -j oe

set -e						# if any error occurs, exit 1

#########
# test runs
# qsub -v bam=${BAM},wd=${WD},od=${OD},sco=${SCO},name=${NAME},\
#  filter_len=${FILTER_LEN},assumptions=${ASSUMPTIONS} run.pbs
cd ${WD}

##################
## EXPAND FLAGS ##
##################
VOLUME=${OD}/${NAME}_${FILTER_LEN}_read_volume.txt
PILEUP=${OD}/${NAME}_${FILTER_LEN}_pileup.out
JOB_ID=$( echo ${PBS_JOBID} | cut -d'.' -f1 )

#################
## GENOME SIZE ##
#################
echo "[Executing ${JOB_ID} run.pbs]" >> ${LOG}

START_TIME=$( date +"%T" )					# records time taken by whole pipeline
START=$( date -u -d "${START_TIME}" +"%s" )


# taking outputs and giving an answer
python3 genomeSize.py -od ${OD} -n ${NAME} -p ${PILEUP} -v ${VOLUME} \
-m ${METHOD} -i ${INDEL} -rc ${R_CLIPPING} -fl ${FILTER_LEN} -pid ${JOB_ID}

FINAL_TIME=$( date +"%T" )
FINAL=$(date -u -d "${FINAL_TIME}" +"%s")

echo "$( date -u -d "0 ${FINAL} sec - ${START} sec" +"%H:%M:%S" ) elapsed" >> ${LOG}

echo "[Finished executing ${JOB_ID} run.pbs]" >> ${LOG}
echo "===========================================================" >> ${LOG}
