
#!/bin/bash

#PBS -l select=1:ncpus=1:mem=4gb
#PBS -l walltime=1:00:00
#PBS -m ae
#PBS -j oe
#PBS -o /srv/scratch/z3452659/BINF6112-Sep20/TeamGenomeSize/output/log


NAME="s_cerevisiae"

cd /srv/scratch/z3452659/BINF6112-Sep20/TeamGenomeSize/output

time=$(date "+%Y.%m.%d-%H.%M.%S")

dirname=$NAME.$time

mkdir $dirname

BAM=$dirname/$NAME.bam


# get bed file
egrep -v "^#" /srv/scratch/z3452659/BINF6112-Sep20/TeamGenomeSize/data/2020-09-22.ReferenceGenomes/$NAME/busco3/run_$NAME/full_table_$NAME.tsv | \
cut -f3,4,5 | \
sed -e 's/\t/ /g' | \
egrep -v '^$' > $dirname/$NAME.bed
sort -n -k 2 $dirname/$NAME.bed > $dirname/$NAME.sorted.bed

module load samtools

cp /srv/scratch/z3452659/BINF6112-Sep20/TeamGenomeSize/data/2020-09-22.ReferenceGenomes/$NAME/bam/$NAME.bam $dirname/
samtools sort -o $dirname/$NAME.sort.bam $dirname/$NAME.bam
samtools index -b $dirname/$NAME.sort.bam
cp $dirname/$NAME.sort.bam.bai $dirname/$NAME.bam.bai
samtools mpileup -BQ0 -l $dirname/$NAME.sorted.bed $dirname/$NAME.bam > $dirname/pileup.out


python3 /home/$USER/GenomeSize/code/depth_file.py $dirname


samtools stats ${BAM} | grep ^RL | cut -f 2- | awk '{total+=$1*$2} END{print total}' >> $dirname/volume
samtools stats ${BAM} | grep ^RL | cut -f 2- | awk '{if($1 >= 5000) total+=$1*$2 } END{print total}' >> $dirname/volume

samtools view $BAM > view.out

python3 indel_clipping_counter.py > indel_clipping_counter_output.txt