#!/bin/bash

#PBS -l select=1:ncpus=1:mem=4gb
#PBS -l walltime=11:30:00
#PBS -j oe
#PBS -o /home/z5206657/GenomeSize/readVolLog

echo "===========================================================" >> log
echo "[Executing indel.pbs]"  >> log

START_TIME=$( date +"%T" )					# records time taken by whole pipeline
START=$( date -u -d "${START_TIME}" +"%s" )
cd /home/z5206657/GenomeSize/code

module load samtools/1.10


#samtools view /srv/scratch/z3452659/BINF6112-Sep20/TeamGenomeSize/data/2020-09-22.ReferenceGenomes/e_coli/bam/e_coli.bam | cut -f 6  > results
samtools stats /srv/scratch/z3452659/BINF6112-Sep20/TeamGenomeSize/data/2020-09-22.ReferenceGenomes/a_thaliana/bam/a_thaliana.bam > stats
samtools view -@ 8 /srv/scratch/z3452659/BINF6112-Sep20/TeamGenomeSize/data/2020-09-22.ReferenceGenomes/a_thaliana/bam/a_thaliana.bam  | cut -f 6  > results
python3 get_indel_clipping.py results > indel_bias.txt


FINAL_TIME=$( date +"%T" )
FINAL=$(date -u -d "${FINAL_TIME}" +"%s")

echo "$( date -u -d "0 ${FINAL} sec - ${START} sec" +"%H:%M:%S" ) elapsed" >> log
echo "[Finished executing indel.pbs]"  >> log
echo "===========================================================" >>log
