#!/bin/bash

#PBS -N indel.pbs
#PBS -l walltime=11:00:00
#PBS -j oe

START_TIME=$( date +"%T" )					# records time taken by whole pipeline
START=$( date -u -d "${START_TIME}" +"%s" )
JOB_ID=$( echo ${PBS_JOBID} | cut -d'.' -f1 )

echo "[Executing ${JOB_ID} indel.pbs]"  >> ${LOG}


module load samtools/1.10

if [[ ! -s ${OD}/${NAME}_${FILTER_LEN}_indel_bias.txt ]]; then
    
  if [[ -s ${OD}/${NAME}_${FILTER_LEN}.cigar ]]; then
      python3 ${WD}/code/indel_bias.py ${OD}/${NAME}_${FILTER_LEN}.cigar
  else
      samtools view -@ ${THREADS} ${OD}/${NAME}_${FILTER_LEN}.bam | cut -f 6 > ${OD}/${NAME}_${FILTER_LEN}.cigar
      python3 ${WD}/code/indel_bias.py ${OD}/${NAME}_${FILTER_LEN}.cigar
  fi

  rm ${OD}/${NAME}_${FILTER_LEN}.cigar
  rm ${OD}/${NAME}_${FILTER_LEN}.bam
  rm ${OD}/${NAME}_${FILTER_LEN}.bam.bai

fi


FINAL_TIME=$( date +"%T" )
FINAL=$(date -u -d "${FINAL_TIME}" +"%s")

echo "$( date -u -d "0 ${FINAL} sec - ${START} sec" +"%H:%M:%S" ) elapsed" >> ${LOG}
echo "[Finished executing ${JOB_ID} indel.pbs]"  >> ${LOG}
echo "===========================================================" >> ${LOG}

