#!/bin/bash

#PBS -l select=1:ncpus=1:mem=4gb
#PBS -l walltime=1:00:00
#PBS -M z5207331@unsw.edu.au
#PBS -m ae
#PBS -j oe
#PBS -o /home/z5207331/GenomeSize/make_pileup_log

cd /home/z5207331/GenomeSize

egrep -v "^#" /srv/scratch/z3452659/BINF6112-Sep20/TeamGenomeSize/data/2020-09-22.ReferenceGenomes/e_coli/busco3/run_e_coli/full_table_e_coli.tsv | \
cut -f3,4,5 | \
sed -e 's/\t/ /g' > /home/z5207331/GenomeSize/e_coli_ss.bed

module load samtools

source venv/bin/activate

python3 code/make_pileup.py

deactivate