#!/bin/bash

#PBS -l select=1:ncpus=1:mem=4gb
#PBS -l walltime=1:00:00
#PBS -m ae
#PBS -j oe
#PBS -o /home/z5207331/GenomeSize/pileup2_log

# cd /home/z5207315/GenomeSize

# egrep -v "^#" /srv/scratch/z3452659/BINF6112-Sep20/TeamGenomeSize/data/2020-09-22.ReferenceGenomes/e_coli/busco3/run_e_coli/full_table_e_coli.tsv | \
# cut -f3,4,5 | \
# sed -e 's/\t/ /g' > /home/$USER/GenomeSize/e_coli_ss.bed

module load samtools

# samtools sort /srv/scratch/z3452659/BINF6112-Sep20/TeamGenomeSize/data/2020-09-22.ReferenceGenomes/e_coli/bam/e_coli.bam -o /srv/scratch/$USER/e_coli.bam
# samtools index -b /srv/scratch/z3452659/BINF6112-Sep20/TeamGenomeSize/data/2020-09-22.ReferenceGenomes/e_coli/bam/e_coli.bam > /srv/scratch/$USER/e_coli.bam.bai

cd /srv/scratch/z5207331


samtools sort -o /srv/scratch/$USER/e_coli.sort.bam /srv/scratch/$USER/e_coli.bam
samtools index -b /srv/scratch/$USER/e_coli.sort.bam
cp /srv/scratch/$USER/e_coli.sort.bam.bai /srv/scratch/$USER/e_coli.bam.bai
samtools mpileup -l /srv/scratch/$USER/e_coli_ss.bed /srv/scratch/$USER/e_coli.bam > /srv/scratch/$USER/pileup.out
sort -n -k 2 e_coli_ss.bed > e_coli_sorted.bed

# source venv/bin/activate

# python3 code/make_pileup.py

# deactivate
