#!/bin/bash

#PBS -l select=1:ncpus=1:mem=4gb
#PBS -l walltime=1:00:00
#PBS -M z5206657@ad.unsw.edu.au
#PBS -m ae
#PBS -j oe
#PBS -o /home/z5206657/GenomeSize/readVolLog

echo " -- changed directory -- "

cd /home/z5206657/GenomeSize/code

echo " -- load samtools --"

module load samtools/1.10

echo " -- run calcReadVolume.sh --"

chmod u+x calcReadVolume.sh

# run with 10kb, 5kb, none - min read cutoff

./calcReadVolume.sh "/srv/scratch/z3452659/BINF6112-Sep20/TeamGenomeSize/data/2020-09-22.ReferenceGenomes/e_coli/bam/e_coli.bam"  10000

./calcReadVolume.sh "/srv/scratch/z3452659/BINF6112-Sep20/TeamGenomeSize/data/2020-09-22.ReferenceGenomes/e_coli/bam/e_coli.bam"  5000

./calcReadVolume.sh "/srv/scratch/z3452659/BINF6112-Sep20/TeamGenomeSize/data/2020-09-22.ReferenceGenomes/e_coli/bam/e_coli.bam"  


