#!/bin/bash

#PBS -N tidy.pbs
#PBS -l walltime=00:05:00
#PBS -j oe

JOB_ID=$( echo ${PBS_JOBID} | cut -d'.' -f1 )
echo "[Executing ${JOB_ID} tidy.pbs]"

# neccesary if needing to share permissions with users within your group to access results
chmod -R 775 ${OD}/

rm ${OD}/${NAME}_${FILTER_LEN}.cigar
rm ${OD}/${NAME}_${FILTER_LEN}.bam
rm ${OD}/${NAME}_${FILTER_LEN}.bam.bai

FINAL_TIME=$( date +"%T" )
FINAL=$(date -u -d "${FINAL_TIME}" +"%s")

echo "===========================================================" >> ${LOG}
echo "$( date -u -d "0 ${FINAL} sec - ${START} sec" +"%H:%M:%S" ) elapsed" >> ${LOG}
echo "[Finished ${JOB_ID} executing tidy.pbs]" >> ${LOG}
echo "===========================================================" >> ${LOG}
echo "===========================================================" >> ${LOG}

